from typing import TextIO
from datetime import datetime


def writeHermesHeader(f: TextIO):
    header = ("/*******\n"
              "This file was generated by Hermes, do not edit\n"
              f"{datetime.now()}\n"
              "*******/\n")
    f.write(header)
